version: '3'
services:
  ec2instances.info:
    build:
      context: .
      args:
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
        - AWS_SESSION_TOKEN
    ports:
      - '8080:8080'
